### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by SinghDivyajeet** [ritwickdey/vscode-live-server#290] opened 2019-02-13 04:25 UTC
[Uploading ritwickdey.LiveServer-unresponsive.cpuprofile.txt…]
- Issue Type: `Performance`
- Extension Name: `LiveServer`
- Extension Version: `5.5.1`
- OS Version: `Windows_NT x64 10.0.17763`
- VSCode version: `1.31.1`

[ritwickdey.LiveServer-unresponsive.cpuprofile.txt](https://github.com/ritwickdey/vscode-live-server/files/2858784/ritwickdey.LiveServer-unresponsive.cpuprofile.txt)
g:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ritwickdey** [comment] 2019-02-13 04:27
please attach the file C:\Users\46div\ritwickdey.LiveServer-unresponsive.cpuprofile.txt

**Comment by ritwickdey** [comment] 2019-02-13 04:29
what's your processor , Ram ?

**Comment by ritwickdey** [comment] 2019-02-13 04:30
and is the Html is so big?

**Comment by ritwickdey** [comment] 2019-02-13 05:00
If you can share reproducible steps that would be even better. (Comment in #278 )


Duplicate of #278

**Closed by ritwickdey** 2019-02-13 05:00 UTC

**Comment by SinghDivyajeet** [comment] 2019-02-14 05:33
Ahh! I got that, I wrote a script that was running on an infinite loop, that's why live sever crashed.

**Comment by ritwickdey** [comment] 2019-02-14 05:57
It should not be..

Can you share the html/js files?
