### ISSUE TITLE
Live server stop working after 1.31 update

### ISSUE THREAD

**Issue by Lukaydo** [ritwickdey/vscode-live-server#274] opened 2019-02-06 21:02 UTC
Issue Type: <b>Bug</b>

dyld: lazy symbol binding failed: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/.../.vscode/extensions/ritwickdey.liveserver-5.3.1/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

dyld: Symbol not found: __ZN2v816FunctionTemplate3NewEPNS_7IsolateEPFvRKNS_20FunctionCallbackInfoINS_5ValueEEEENS_5LocalIS4_EENSA_INS_9SignatureEEEiNS_19ConstructorBehaviorENS_14SideEffectTypeE
  Referenced from: /Users/.../.vscode/extensions/ritwickdey.liveserver-5.3.1/node_modules/fsevents/lib/binding/Release/node-v64-darwin-x64/fse.node
  Expected in: flat namespace

Extension version: 5.3.1
VS Code version: Code 1.31.0 (7c66f58312b48ed8ca4e387ebd9ffe9605332caa, 2019-02-05T22:32:14.164Z)
OS version: Darwin x64 18.2.0

<details>
<summary>System Info</summary>

|Item|Value|
|---|---|
|CPUs|Intel(R) Core(TM) i5-6360U CPU @ 2.00GHz (4 x 2000)|
|GPU Status|2d_canvas: enabled<br>checker_imaging: disabled_off<br>flash_3d: enabled<br>flash_stage3d: enabled<br>flash_stage3d_baseline: enabled<br>gpu_compositing: enabled<br>multiple_raster_threads: enabled_on<br>native_gpu_memory_buffers: enabled<br>rasterization: enabled<br>surface_synchronization: enabled_on<br>video_decode: enabled<br>webgl: enabled<br>webgl2: enabled|
|Load (avg)|2, 2, 3|
|Memory (System)|8.00GB (0.08GB free)|
|Process Argv||
|Screen Reader|no|
|VM|0%|

</details>

**Comment by travisseh** [comment] 2019-02-06 21:20
After the most recent VS update I'm also getting the following error: "Extension Host Terminated" and restarting it won't work. I had to disable Live Server in order to get VS to work at all. 

Extension version: 5.3.1
VS Code version: Version 1.31.0 (1.31.0)

**Comment by irisida** [comment] 2019-02-06 21:25
Same error as above. 
5.3.1
1.31.0

**Comment by buzrocks** [comment] 2019-02-06 21:34
Yes same here.
Live Server 5.3.1
VS Code 1.3.1.0

I had to go all the way back to 4.1.0 to get it working again. (on Mojave)Just go to extension settings/ live server/ settings and and "install another version"

**Comment by Lukaydo** [comment] 2019-02-06 21:52
Hello, this help me to solve the problem:
https://github.com/ritwickdey/vscode-live-server/issues/273#issuecomment-461185641

Update Live server to version 5.4.0 via vsix file
https://github.com/ritwickdey/vscode-live-server/releases

**Comment by kofiasare** [comment] 2019-02-06 22:33
Same issue after update to vscode version 1.31

**Comment by adesugbaa** [comment] 2019-02-06 23:01
Please try the 5.4.0 in the Releases tab.

We are awaiting feedback before publishing it to the Visual Studio Marketplace.

**Comment by adesugbaa** [comment] 2019-02-07 00:45
Please download 5.4.0 from this repo (under Releases), and try installing that manually.

```
View -> Command Pallete... -> Extensions Install from VSIX...
```

**Comment by ritwickdey** [comment] 2019-02-07 02:54
Please install v5.4.0 from marketplace. This issue has been fixed!

// Duplicate of #273

**Closed by ritwickdey** 2019-02-07 02:54 UTC
