### ISSUE TITLE
 How can I enable CORS (Cross-Origin Resource Sharing) ?

### ISSUE THREAD

**Issue by garaving** [ritwickdey/vscode-live-server#68] opened 2018-01-24 08:10 UTC
Failed to load http://xxxxxx.com//assets/i18n/it.json: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://127.0.0.1:5500' is therefore not allowed access.

**Comment by ritwickdey** [comment] 2018-01-24 08:27
Same as https://github.com/ritwickdey/vscode-live-server/issues/64

**Comment by ritwickdey** [comment] 2018-02-13 19:27
This features is already added in v3.1.0.  (Sorry, I forget to close it)

**Closed by ritwickdey** 2018-02-13 19:27 UTC
Labels: Feature Requested, enhancement, help wanted

**Comment by amirblum** [comment] 2018-03-24 14:56
It seems like CORS still isn't enabled on the local server. I tested using test-cars.org and returns an error when trying to GET one of the files from the server. Any additional steps I'm missing? Anything that needs to be enabled in the settings?

**Comment by Beta6484** [comment] 2018-08-29 22:54
I still can't access .json files from external domains. Am I forgetting to set something up?

**Comment by JonathanWilbur** [comment] 2018-12-08 01:45
![acao](https://user-images.githubusercontent.com/20342114/49680311-1243b900-fa61-11e8-9055-41728de6c683.PNG)

**Comment by JammiM** [comment] 2019-01-16 21:55
I have also encountered a CORS issue when trying to request a API, are you sure that you have CORS enabled ?

I'm using Safari version 11.1.2

**Comment by SuperRoach** [comment] 2019-02-11 12:40
Using 5.4.0, I'm getting the same problem when trying to call https://api.flickr.com/services . This is with Firefox.

**Comment by veuncent** [comment] 2019-05-09 15:40
Same issue here in Chrome, Firefox and Edge on Windows 10

**Comment by larryhu** [comment] 2019-05-31 02:57
Temporary suggestion ->  https://github.com/ritwickdey/vscode-live-server/issues/249#issuecomment-497557001

**Comment by sekti92** [comment] 2021-05-20 21:41
Hey I have the same issue when using d3.js. How to fix this issue?

```
d3.html('http://enable-cors.org')
  .get((err, data) => {
    console.log(data)
  })
```
![image](https://user-images.githubusercontent.com/14885417/119052092-42436480-b9ee-11eb-9da3-8bc2264ee742.png)

**Comment by GoudronViande24** [comment] 2022-04-18 18:33
Still hasn't been fixed.

**Comment by RafaPatino01** [comment] 2022-04-26 02:26
Same problem 

XHRGEThttp://example.com/movies.json
[HTTP/1.1 404 Not Found 81ms]

Cross-Origin Request Blocked: The Same Origin Policy disallows reading the remote resource at http://example.com/movies.json. (Reason: CORS header ‘Access-Control-Allow-Origin’ missing). Status code: 404.

Uncaught (in promise) TypeError: NetworkError when attempting to fetch resource.
GEThttp://127.0.0.1:5500/favicon.ico

**Comment by shadynasrat** [comment] 2022-05-19 15:57
Still some times its not working... please fix this

**Comment by sgalcheung** [comment] 2022-05-20 04:25
It's worked for me, I use the latest Live Server v5.7.5

It is not the npm live server， have you mistake? this is vscode live server

**Comment by vacing** [comment] 2022-12-08 07:44
https://marketplace.visualstudio.com/items?itemName=yandeu.five-server

maybe use five-server instead

**Comment by asitanc** [comment] 2022-12-22 09:36
_Access-Control-Allow-Origin_ can have three possible directives (*, origin, or null) to tell the browser from which _origin_ can one access certain resources.

The issue is with the response from the **backend** which is/was missing appropriate header. Thats why the issue is occurring "sometimes"; with some URLs or with other tools as well. And it should be unrelated to liveserver in vscode.

_One cannot fetch a resource that they are not allowed to fetch._

So, your backend should return response with header _Access-Control-Allow-Origin_ as wildcard (*) or specify the origin. If you specify the origin, the origin **must** match with your server (if you make request from example.com; the origin must be example.com).

You can check the headers using _cURL_ with _--head_ parameter for further troubleshooting of the backend responses.

Also, some sources are available here:
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
- https://web.dev/introduction-to-fetch/

There is also very very nice explanation of how the header works here:
- https://stackoverflow.com/questions/10636611/how-does-the-access-control-allow-origin-header-work

**Comment by youyinnn** [comment] 2023-03-03 04:12
It still got blocked, 5.7.9.

**Comment by youyinnn** [comment] 2023-03-03 04:14
> https://marketplace.visualstudio.com/items?itemName=yandeu.five-server
> 
> maybe use five-server instead

Same...
