### ISSUE TITLE
Live Server is not opening tabs.

### ISSUE THREAD

**Issue by Niuniu32** [ritwickdey/vscode-live-server#135] opened 2018-05-24 00:47 UTC
So i press live server and it loads port 5500, but it doesn't open a browser.
No error code or anything. If i type in the port number and loaded in chrome it shows the website and sometime it would auto update.
It is weird and i tried the "liveServer.settings.CustomBrowser":"chrome:PrivateMode", any kind of browser typed in won't work.
It is really weird.
Any idea what is happening
Spec is:
VCS:1.23.1
Live Server:4.0.0
Chrome:66.0.3359.181
Running on a Surface Pro 4 Locally

**Comment by rjoydip** [comment] 2018-05-24 03:47
Please try to set browser manually with `liveServer.settings.CustomBrowser` (with only `chrome` not with `chrome:PrivateMode`) settings or `liveServer.settings.AdvanceCustomBrowserCmdLine` and check whether it's working or not.

Example: 
> settings.json (User settings)

```json
{
   "liveServer.settings.CustomBrowser":"chrome"
}
```
or,
```json
{
   "liveServer.settings.AdvanceCustomBrowserCmdLine":"C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe"
}
```

**Comment by manolinjr81** [comment] 2018-05-25 08:47
I am having the same problem. I tried the proposed solution but it didn't work either. The server runs on localhost:5500 but the it doesn't open the browser. I also tried changing the port number by the way.

**Comment by rjoydip** [comment] 2018-05-27 18:40
Strange I don't understand why this is not working. Can you reproduce something so that it is understandable to me?

**Comment by Niuniu32** [comment] 2018-05-28 22:07
It's just live server is not auto opening the browser. And i tried all the liveserver setting for chrome and cmd line thing too, but it won't open. I have to manually type in the port and IP in order to get the live server opening.
It is a little inconvenient so i thought someone knows a solution.
I tried reinstall VCS and Live server and that didn't work either.

**Comment by ritwickdey** [comment] 2018-05-31 16:46
Can you share a screenshot of your settings?

**Comment by rjoydip** [comment] 2018-06-16 04:19
I am closing this issue due to new feedback. Feel free to reopen it.

**Closed by rjoydip** 2018-06-16 04:19 UTC
Labels: need feedback

**Comment by xtinegbyrn** [comment] 2018-09-12 10:16
Hi I need help with this. 

Instead of getting the output. I got this instead.
![image](https://user-images.githubusercontent.com/40625814/45418761-e5794300-b6b7-11e8-8d37-0a70ae40dda5.png)

**Comment by xtinegbyrn** [comment] 2018-09-12 10:18
an urgent respond is appreciated :)

**Comment by winniebosy** [comment] 2019-03-07 14:28
Having the same issue as @xtinebyrn..Kindly assist

**Comment by JoshuaNduwayo** [comment] 2020-08-06 17:45
Here's what worked for me, hope it helps:
![hmmhmm](https://user-images.githubusercontent.com/44451916/89564433-033f7c00-d7eb-11ea-9330-8f96fc74cace.jpg)

**Comment by redhawk5200** [comment] 2023-02-21 14:23
Having the same issue as @

> ![image](https://user-images.githubusercontent.com/108489036/207565218-8931b089-0aa9-4dde-9729-7cb62a556453.png)
> 
> Please help. I always used live server and it always opened a tab when I would press "Go Live" button at the bottom of VS Code. But after I tried to use the terminal to see what gets logged to the console (node main command) instead of using chrome's console, my "Go Live" button stopped opening tabs. I tried so many solutions, including this one, and nothing works. Please help :c Could it be that node js somehow broke live server? Or is it a coincidence? I tried re installing live server but it didn't help.

Having the same issue please help

**Comment by p3yn** [comment] 2023-03-20 02:08
Maybe too late..... but if someone find it useful... Happend to me when im working on subfolders... I "fixed" closing working folder/subfolder on vscode, then opening working folder as root... I dont know if I explain myself... HTML need to be in root working folder... otherwise wont open tab in any browser for me, as today still had to do this in order to liver server works, vscode plu plus had same issue for me... hope it helps!

**Comment by SteaneMurphy** [comment] 2024-04-08 01:58
This is some of the most garbage help I've seen since Microsoft Answers. The issue people are having are that the pop-up that says "don't show again" in relation to the live server pop-up notification. Due to permissions, VSCode requires some people to manually click the pop-up to launch the server in a new browser window.

If a user turns off notifications, there is no way to 'launch' a new browser window, regardless of the live server settings in the JSON file.

This is basic functionality that has not been accounted for in the design of this extension. A setting, somewhere in VSCode is changed due to clicking on this notification, and it is like finding a needle in a haystack to turn the functionality back on.

**Comment by arifkhan247** [comment] 2025-11-12 17:13
> So i press live server and it loads port 5500, but it doesn't open a browser. No error code or anything. If i type in the port number and loaded in chrome it shows the website and sometime it would auto update. It is weird and i tried the "liveServer.settings.CustomBrowser":"chrome:PrivateMode", any kind of browser typed in won't work. It is really weird. Any idea what is happening Spec is: VCS:1.23.1 Live Server:4.0.0 Chrome:66.0.3359.181 Running on a Surface Pro 4 Locally



The solution was go your :ControlPanel>system and security>system>advance system settings > Environment variable> path if there was C windows \system32.  If not then changa it ok
