### ISSUE TITLE
Code Helper Overloads CPU

### ISSUE THREAD

**Issue by user921** [ritwickdey/vscode-live-server#26] opened 2017-09-19 15:30 UTC
Hi! Your plugin causes cpu overload in this code [https://github.com/user921/live-server-cpu-overload](https://github.com/user921/live-server-cpu-overload).

* vscode 1.16.1 (1.16.1)
* macOS Sierra 10.12.6

Process "Code Helper" begins to overload just right after I press "go live".
Looks like this is similar to [https://github.com/Microsoft/vscode/issues/11096](https://github.com/Microsoft/vscode/issues/11096)

**Comment by ritwickdey** [comment] 2017-09-19 15:53
I am using Windows10. I am not getting high CPU usage or CPU overload as you maintained here. (For  

I need few info.

1. Is the HTML page to big in size ? 
2. Can you send me screenshot ? 
3. What are other extensions installed on your system? 
4. Please set the `"liveServer.settings.NoBrowser" : true`. and now press to "Go Live". Are you still getting the CPU Overload?

**Comment by bestvow** [comment] 2017-10-05 03:20
Not open liveServer 
<img width="815" alt="2017-10-05 11 03 24" src="https://user-images.githubusercontent.com/24888709/31209368-0c38eb06-a950-11e7-9ae2-99737427c37c.png">

When open liveServer heavy cpu load

<img width="641" alt="2017-10-05 11 02 26" src="https://user-images.githubusercontent.com/24888709/31209369-0c9d8f20-a950-11e7-8f5f-80ee05d4e7d7.png">
<img width="815" alt="2017-10-05 11 01 46" src="https://user-images.githubusercontent.com/24888709/31209370-0c9ef9b4-a950-11e7-9734-52f72b132ebf.png">
<img width="815" alt="2017-10-05 10 59 23" src="https://user-images.githubusercontent.com/24888709/31209371-0ce5c02e-a950-11e7-955c-d40224d61cda.png">

For same info

- VSCode Version: Code 1.16.1 (27492b6bf3acb0775d82d2f87b25a93490673c6d, 2017-09-14T16:24:39.530Z)
- OS Version: Darwin x64 17.0.0
- Extensions: 

Extension|Author (truncated)|Version
---|---|---
bracket-pair-colorizer|Coe|0.10.9
vscode-markdownlint|Dav|0.10.1
Angular-BeastCode|Mik|5.0.1
vscode-javascript-snippet-pack|aka|0.1.5
auto-rename-tag|for|0.0.14
live-html-previewer|hdg|0.3.0
vscode-auto-open-markdown-preview|hnw|0.0.4
path-autocomplete|ion|1.6.1
vscode-JS-CSS-HTML-formatter|lon|0.2.3
HTMLHint|mka|0.4.0
live-sass|rit|0.5.1
LiveServer|rit|2.2.0
convert-markdown-to-html|sak|5.8.1

(1 theme extensions excluded)

I don't think this cause other extensions
The page which I used for test is very small

If you need more info you can tell me .

**Comment by ritwickdey** [comment] 2017-10-05 05:50
Okay! When the issue is started? I meant, on the extension load time? or after clicking to 'go live'?

If it is after clicking to 'go live',
Is the HTML is too big? , please set following setting and look the performance.
```json
"liveServer.settings.NoBrowser" : true,
"liveServer.settings.ignoreFiles": [
          "*",
          "**"
 ] 

```


[actually i don't have any MAC, on Windows, I am not getting any Performance Issue (If work-space is containing large file (eg 100MB)) ]

**Comment by bestvow** [comment] 2017-10-05 07:27
Awesome , your right !

The folder `node_modules` lead to this problem

<img width="1280" alt="2017-10-05 3 08 06" src="https://user-images.githubusercontent.com/24888709/31214953-44893ea2-a973-11e7-80e1-1380314d05c4.png">


<img width="1280" alt="2017-10-05 3 10 22" src="https://user-images.githubusercontent.com/24888709/31214956-4704e73a-a973-11e7-97d5-4c0c2faf0363.png">

On MAC the `node_modules` folder is a normal folder , liverServer watching every file here ,  however there has  tens of thousands of files (different project different size , but always huge numbers)

![image](https://user-images.githubusercontent.com/24888709/31215221-454228a8-a974-11e7-8ef2-4636f1b91e85.png)

**Comment by ritwickdey** [comment] 2017-10-05 07:55
Okay, That's great, Thanks for the feedback. I'm going to add `**/node_modules/**` in default settings.

**Comment by ritwickdey** [comment] 2017-10-05 07:58
btw, before doing this, let me know, is it working? `**/node_modules/**`  not `/node_modules/**` ?

**Comment by bestvow** [comment] 2017-10-05 08:09
In fact I don't know the different between `**/node_modules/** not /node_modules/**`

but both of them are ok to fix this problem

Using `**/node_modules/**` cpu usage is normal too .

![image](https://user-images.githubusercontent.com/24888709/31216811-7fda9f9e-a97a-11e7-9984-c048ed3a6dcf.png)

**Comment by ritwickdey** [comment] 2017-10-05 08:20
Thanks again 😄 .

Actually, 
`node_modules/**` means `node_modules` directory starting from root.
* e.g. :
if your work-space root is `/usr/project/`
`/usr/project/node_modules/files` => passed.
`/usr/project/subfolder/node_modules/files` => failed.

`**/node_modules/**` any directory named `node_modules`.
* e.g. :
if your work-space root is `/usr/project/`
`/usr/project/node_modules/files` => passed.
`/usr/project/subfolder/node_modules/files` => passed.

**Comment by bestvow** [comment] 2017-10-05 08:24
Got it ！ Thanks

**Comment by ritwickdey** [comment] 2017-10-07 10:10
This issue is resolved in v2.2.1. Please update the extension. - AND no need to set explicit setting for `**/node_modules/** ` for it.

I'm now closing this issue. Let me know if it's resolved for you or not.  😄

**Closed by ritwickdey** 2017-10-07 10:10 UTC
Labels: enhancement, Need More Info

**Comment by halukkaramete** [comment] 2017-12-02 16:38
Latest version shows as 1.18  -> https://code.visualstudio.com/download

And I'm running latest (1.18.1)

Yet, my CPU is 134% ( thanks to CodeHelper ) and mac fan is always on now -- which is a new phenomenon. 

What steps do I need to do to kill/by pass this CodeHelper?

**Comment by oliyg** [comment] 2018-05-15 15:42
thx

**Comment by NiNJAD3vel0per** [comment] 2019-03-10 21:59
my CPU usage is 100% whenever turn on live-server; !!!
Should be fixed ! I am using the lastest ver.

**Comment by Jarrio** [comment] 2020-01-26 23:10
![](https://media.discordapp.net/attachments/286539751513915393/671128881981554688/unknown.png)
Can confirm this still appears to be an issue on `1.41.1`. Closing VSCode does not end the task either for some odd reason, got to force quit.

**Comment by drabastomek** [comment] 2021-06-01 20:04
Confirming this is still an issue on 6/1.

**Comment by CoMatu** [comment] 2023-05-24 09:26
My CPU usage is over 400% ....
<img width="642" alt="image" src="https://github.com/ritwickdey/vscode-live-server/assets/30466272/76fa607d-8e82-4b4d-8c1a-15c358a3a53b">

iMac 2019, intelCore i5

Live Server
v5.7.9
