### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Xenorage** [ritwickdey/vscode-live-server#295] opened 2019-02-17 15:08 UTC
- Issue Type: `Performance`
- Extension Name: `LiveServer`
- Extension Version: `5.5.1`
- OS Version: `Windows_NT x64 6.1.7601`
- VSCode version: `1.31.0`

:warning: Make sure to **attach** this file from your *home*-directory: `e:\symlinks\Dns\ritwickdey.LiveServer-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by viditvarshney** [comment] 2019-02-17 16:14
- This issue already opened and pinned also 
referenced to #278

**Comment by ritwickdey** [comment] 2019-04-08 11:45
Hello. few questions!!, 
  
When you're getting this issue? after load of vscode or after clicking to Go Live ?
Is this happen every-time ? or random ?

Please reply here https://github.com/ritwickdey/vscode-live-server/issues/278

Duplicate of https://github.com/ritwickdey/vscode-live-server/issues/278
> [Note: This issue is closed by a javascript code (written by me).
https://gist.github.com/ritwickdey/36682dabe4a992c57e4562c935bfbbdd ]
Thank You.

**Closed by ritwickdey** 2019-04-08 11:45 UTC
