### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by dtvn** [ritwickdey/vscode-live-server#279] opened 2019-02-07 22:10 UTC
- Issue Type: `Performance`
- Extension Name: `LiveServer`
- Extension Version: `5.4.0`
- OS Version: `Windows_NT ia32 10.0.17134`
- VSCode version: `1.31.0`

:warning: [ritwickdey.LiveServer-unresponsive.cpuprofile.txt](https://github.com/ritwickdey/vscode-live-server/files/2842833/ritwickdey.LiveServer-unresponsive.cpuprofile.txt) :warning:

![running extensions report](https://user-images.githubusercontent.com/43217335/52446184-d5c73300-2b5f-11e9-9437-795dcff61e18.png)

**Comment by ritwickdey** [comment] 2019-02-12 07:52
Can you please share a screenshot of your workspace in comment of #278  ?

// Duplicate of 278#

**Closed by ritwickdey** 2019-02-12 07:52 UTC

**Comment by ritwickdey** [comment] 2019-02-12 10:31
Please upgrade the extension to lastest version (I've updated it recently). 

If it doesn't work, please let me know in comment of #278

**Comment by LeoTheCoder16** [comment] 2019-09-06 22:07
It doesnt work
