### ISSUE TITLE
Live Server doesn't work with multi-root workspaces

### ISSUE THREAD

**Issue by AlexandruVoica** [ritwickdey/vscode-live-server#128] opened 2018-05-19 15:36 UTC
Hey, 

First of all, this extension is amazing. 

_I just want to give you a heads-up that I was not able to make Live Server work when I have multiple projects open in the same VS Code window (something called a multi-root workspace in the official documentation). In this situation, the extension would open a new Chrome tab for me, but it would load up some completely different resources (HTML, JS etc.). I've tried all of the methods specified in your documentation. None of them worked._

I've solved this by using another extension that can manage my projects and workspaces (Project Manager) and now, when only one project is open, Live Server works perfectly.

Live Server v4.0.0
VS Code v1.23.1

**Comment by mxschmitt** [comment] 2018-05-19 16:03
Duplicate of #43 and thanks for your feedback 👍

**Closed by mxschmitt** 2018-05-19 16:03 UTC
Labels: duplicate
