### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by matrixersp** [ritwickdey/vscode-live-server#297] opened 2019-02-18 09:03 UTC
- Issue Type: `Performance`
- Extension Name: `LiveServer`
- Extension Version: `5.5.1`
- OS Version: `Linux x64 4.18.0-15-generic`
- VSCode version: `1.31.1`

[ritwickdey.LiveServer-unresponsive.cpuprofile.txt](https://github.com/ritwickdey/vscode-live-server/files/2874746/ritwickdey.LiveServer-unresponsive.cpuprofile.txt)

**Comment by viditvarshney** [comment] 2019-02-18 09:41
Check This issue is already Opened 
/check_and_then_create_issue  @matrixersp

**Comment by ritwickdey** [comment] 2019-04-08 11:45
Hello. few questions!!, 
  
When you're getting this issue? after load of vscode or after clicking to Go Live ?
Is this happen every-time ? or random ?

Please reply here https://github.com/ritwickdey/vscode-live-server/issues/278

Duplicate of https://github.com/ritwickdey/vscode-live-server/issues/278
> [Note: This issue is closed by a javascript code (written by me).
https://gist.github.com/ritwickdey/36682dabe4a992c57e4562c935bfbbdd ]
Thank You.

**Closed by ritwickdey** 2019-04-08 11:45 UTC
