### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by hsoot** [ritwickdey/vscode-live-server#286] opened 2019-02-12 12:45 UTC
[ritwickdey.LiveServer-unresponsive.cpuprofile.txt](https://github.com/ritwickdey/vscode-live-server/files/2855810/ritwickdey.LiveServer-unresponsive.cpuprofile.txt)
- Issue Type: `Performance`
- Extension Name: `LiveServer`
- Extension Version: `5.5.0`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/Xave/ritwickdey.LiveServer-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ritwickdey** [comment] 2019-02-13 05:00
If you can share reproducible steps that would be even better. (Comment in #278 )

Duplicate of #278

**Closed by ritwickdey** 2019-02-13 05:00 UTC
