### ISSUE TITLE
:last-child and :last-of-type are not working when open with live server

### ISSUE THREAD

**Issue by iamsirid** [ritwickdey/vscode-live-server#174] opened 2018-07-25 08:48 UTC
## I'm submitting a...

```html
[ ] Regression (a behavior that used to work and stopped working in a new release)
[x] Bug report  <!-- Please search GitHub for a similar issue or PR before submitting -->
[ ] Feature request
[ ] Documentation issue or request
[ ] Other: <!-- Please describe: -->
```

## Current behavior

css pseudo-classes :last-child and :last-of-type are not working with div element when open with live server

index.html
![index.html](https://image.ibb.co/ezE1jT/index.jpg)

main.css
![main.css](https://image.ibb.co/hSoiyo/css.jpg)

On live server (no border on last div element)
![live server](https://image.ibb.co/m59Z4T/live_server.jpg)

## Expected behavior
Open index.html directly (there is a border on last div element )
![direct](https://image.ibb.co/fae1jT/direct.jpg)

## Environment

```html
Browser:

- [X] Chrome (desktop) version 67.0.3396.99
- [ ] Firefox version XX
- [ ] Safari (desktop) version XX
- [ ] IE version XX
- [ ] Edge version XX
--




For Tooling issues:

- Live Server: 5.1.1
- Platform:  Windows 10 64 bits
- Visual Studio Code: 1.25.1
```

**Comment by rjoydip** [comment] 2018-07-25 18:17
@iamsirid I don't think this is vscode-liveserver issue. Maybe you are writing the wrong CSS. I have checked it. You can see this [link](https://stackblitz.com/edit/vscode-liveserver-issue-174?file=style.css). I am not good at CSS.

**Comment by ritwickdey** [comment] 2018-07-25 19:00
Hi, this is not a bug & you're CSS is correct. But the issue is (I believe) you're using any chrome extension that creates extra `div` as the last child (most of the extension do, they create an extra div element to add their UI and makes visible depending on conditions)


*Workaround:* Either disable all extension or open in incognito window or guest window/

**Comment by ritwickdey** [comment] 2018-07-25 19:04
Hi @rjoydip, thanks for try. 

This is ```div:last-child{}```. not, ```div::last-child{}```

![image](https://user-images.githubusercontent.com/18099464/43221791-89ab6a5c-906b-11e8-9eb0-51cfc93952bf.png)

**Comment by iamsirid** [comment] 2018-07-26 00:20
Hi @rjoydip and @ritwickdey, thanks for reply.

I try open it in incognito mode on different browsers. The result still the same (Chrome, Opera, IE)
![compare-browser](https://user-images.githubusercontent.com/6850971/43234048-017582d8-90a4-11e8-89db-05e53febac05.jpg)

Maybe it's the live server that creates extra div as the last child ?



index.html and main.css 
[source-code.zip](https://github.com/ritwickdey/vscode-live-server/files/2229968/source-code.zip)

**Comment by ritwickdey** [comment] 2018-07-26 05:42
Try `div:last-of-type { }`

**Comment by rjoydip** [comment] 2018-11-25 04:19
Closing due to no-activity

**Closed by rjoydip** 2018-11-25 04:19 UTC
Labels: question

**Comment by jomilto** [comment] 2019-09-17 18:33
This lines are not working with live server.
```
p:last-child {
    color: brown;
}
```

**Comment by Crumbled-potato** [comment] 2020-04-15 09:17
I am still waiting for the answer.

**Comment by timonson** [comment] 2020-06-13 21:15
bump, same issue with live-server here.

**Comment by timonson** [comment] 2020-06-13 21:17
@rjoydip can you reopen this issue please? It is not solved yet.

**Comment by israelfxd** [comment] 2022-10-21 17:07
I was looking for someone with the same problem, and that's exactly it, when opened without Live Server it works correctly.

**Comment by tano1709** [comment] 2023-01-31 15:55
Buenas, estuve con este mismo tema, y como decian es un tema de la etiqueta <script> que agrega Live Server al final del html, entonces el CSS lo toma como ultimo hijo del body y asi no se ve reflejado el estilo que asignamos a ":last-child", lo que pude hacer para ver que se refleje el estilo es ir a la consola de desarrollo y editar el html, quitando las lineas contenidas en el <script>:

`<script>
	// <![CDATA[  <-- For SVG support
	if ('WebSocket' in window) {
		(function () {
			function refreshCSS() {
				var sheets = [].slice.call(document.getElementsByTagName("link"));
				var head = document.getElementsByTagName("head")[0];
				for (var i = 0; i < sheets.length; ++i) {
					var elem = sheets[i];
					var parent = elem.parentElement || head;
					parent.removeChild(elem);
					var rel = elem.rel;
					if (elem.href && typeof rel != "string" || rel.length == 0 || rel.toLowerCase() == "stylesheet") {
						var url = elem.href.replace(/(&|\?)_cacheOverride=\d+/, '');
						elem.href = url + (url.indexOf('?') >= 0 ? '&' : '?') + '_cacheOverride=' + (new Date().valueOf());
					}
					parent.appendChild(elem);
				}
			}
			var protocol = window.location.protocol === 'http:' ? 'ws://' : 'wss://';
			var address = protocol + window.location.host + window.location.pathname + '/ws';
			var socket = new WebSocket(address);
			socket.onmessage = function (msg) {
				if (msg.data == 'reload') window.location.reload();
				else if (msg.data == 'refreshcss') refreshCSS();
			};
			if (sessionStorage && !sessionStorage.getItem('IsThisFirstTime_Log_From_LiveServer')) {
				console.log('Live reload enabled.');
				sessionStorage.setItem('IsThisFirstTime_Log_From_LiveServer', true);
			}
		})();
	}
	else {
		console.error('Upgrade your browser. This Browser is NOT supported WebSocket for Live-Reloading.');
	}
	// ]]>
</script>
`

y automaticamente se ve el estilo usado en CSS. No es muy cómodo pero sirve para ese caso puntual

Espero que les sirva...Saludos !!!
