### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by Codebrother1** [ritwickdey/vscode-live-server#291] opened 2019-02-13 16:40 UTC
- Issue Type: `Performance`
- Extension Name: `LiveServer`
- Extension Version: `5.5.1`
- OS Version: `Darwin x64 18.2.0`
- VSCode version: `1.31.1`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/terrancecazy/ritwickdey.LiveServer-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ritwickdey** [comment] 2019-04-08 11:42
Hello. few questions!!, 
  
When you're getting this issue? after load of vscode or after clicking to Go Live ?
Is this happen every-time ? or random ?

Please reply here https://github.com/ritwickdey/vscode-live-server/issues/278

Duplicate of https://github.com/ritwickdey/vscode-live-server/issues/278

> [Note: This issue is closed by a javascript code (written by me).
https://gist.github.com/ritwickdey/36682dabe4a992c57e4562c935bfbbdd ]

Thank You.

**Closed by ritwickdey** 2019-04-08 11:42 UTC
