### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by anyfre** [ritwickdey/vscode-live-server#394] opened 2019-04-04 12:11 UTC
- Issue Type: `Performance`
- Extension Name: `LiveServer`
- Extension Version: `5.5.1`
- OS Version: `Linux x64 4.15.0-20-generic`
- VSCode version: `1.32.3`

:warning: Make sure to **attach** this file from your *home*-directory: `/home/nao/ritwickdey.LiveServer-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ritwickdey** [comment] 2019-04-08 11:22
Hello, few questions, 
  
When you're getting this issue? after load of vscode or after clicking to Go Live ?
Is this happen every-time ? or random ?

Please reply here https://github.com/ritwickdey/vscode-live-server/issues/278

Duplicate of https://github.com/ritwickdey/vscode-live-server/issues/278

> [Note: This issue is closed by a javascript code (written by me).
https://gist.github.com/ritwickdey/ddf2ff0e3ca49354b773a4c4ce8cb53c]

**Closed by ritwickdey** 2019-04-08 11:22 UTC

**Comment by anyfre** [comment] 2019-04-08 11:28
I am Japanese.
My weak point is English.
Therefore, I can not answer appropriately.
I'm sorry.🙇

2019年4月8日(月) 20:22 Ritwick Dey <notifications@github.com>:

**Comment by anyfre** [comment] 2019-04-08 11:30
to answer.
It happens randomly.

**Comment by ritwickdey** [comment] 2019-04-08 12:12
Hi @anyfre. not a problem - even I'm not good in english. 

Just another one question, is this happened just after clicking to "Go Live" ?

**Comment by anyfre** [comment] 2019-04-08 12:14
yes

2019年4月8日(月) 21:13 Ritwick Dey <notifications@github.com>:
