### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by uryu-myao** [ritwickdey/vscode-live-server#284] opened 2019-02-12 07:47 UTC
- Issue Type: `Performance`
- Extension Name: `LiveServer`
- Extension Version: `5.4.0`
- OS Version: `Darwin x64 18.0.0`
- VSCode version: `1.31.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/econosys/ritwickdey.LiveServer-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ritwickdey** [comment] 2019-02-12 07:54
Can you please share a screenshot of your workspace in comment of #278  ?

// Duplicate of #278

**Closed by ritwickdey** 2019-02-12 07:54 UTC

**Comment by ritwickdey** [comment] 2019-02-12 10:31
Please upgrade the extension to lastest version (I've updated it recently). 

If it doesn't work, please let me know in comment of #278
