### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by LeonardAchanya** [ritwickdey/vscode-live-server#280] opened 2019-02-09 11:34 UTC
- Issue Type: `Performance`
- Extension Name: `LiveServer`
- Extension Version: `5.4.0`
- OS Version: `Darwin x64 17.7.0`
- VSCode version: `1.31.0`

:warning: Make sure to **attach** this file from your *home*-directory: `/Users/Waveynerd/ritwickdey.LiveServer-unresponsive.cpuprofile.txt` :warning:

Find more details here: https://github.com/Microsoft/vscode/wiki/Explain:-extension-causes-high-cpu-load

**Comment by ritwickdey** [comment] 2019-02-12 07:53
Can you please share a screenshot of your workspace in comment of #278  ?

// Duplicate of #278

**Closed by ritwickdey** 2019-02-12 07:53 UTC

**Comment by ritwickdey** [comment] 2019-02-12 10:31
Please upgrade the extension to lastest version (I've updated it recently). 

If it doesn't work, please let me know in comment of #278

**Comment by LeonardAchanya** [comment] 2019-02-15 20:05
> Please upgrade the extension to lastest version (I've updated it recently).
> 
> If it doesn't work, please let me know in comment of #278

it's been fixed . thanks

**Comment by LeonardAchanya** [comment] 2019-02-15 20:05
fixed guys, thanks
